### ISSUE TITLE
上传错误：Callback must be a function

### ISSUE THREAD

**Issue by 317482454** [HeadingMobile/fabu.love#12]
详细错误信息：
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:127:9)
    at Object.exists (fs.js:195:3)
    at CertDownloader.pem (/root/fabu.love-master/server/node_modules/cert-downloader/index.js:96:18)
    at CertDownloader.verify (/root/fabu.love-master/server/node_modules/cert-downloader/index.js:131:11)
    at module.exports (/root/fabu.love-master/server/node_modules/provisioning/index.js:7:10)
    at /root/fabu.love-master/server/node_modules/ipa-metadata/node_modules/async/lib/async.js:731:23
    at /root/fabu.love-master/server/node_modules/ipa-metadata/node_modules/async/lib/async.js:673:13
    at /root/fabu.love-master/server/node_modules/ipa-metadata/node_modules/async/lib/async.js:230:13
    at _arrayEach (/root/fabu.love-master/server/node_modules/ipa-metadata/node_modules/async/lib/async.js:81:9)
    at _each (/root/fabu.love-master/server/node_modules/ipa-metadata/node_modules/async/lib/async.js:72:13)
    at async.forEachOf.async.eachOf (/root/fabu.love-master/server/node_modules/ipa-metadata/node_modules/async/lib/async.js:229:9)
    at _parallel (/root/fabu.love-master/server/node_modules/ipa-metadata/node_modules/async/lib/async.js:672:9)
    at Object.async.parallel (/root/fabu.love-master/server/node_modules/ipa-metadata/node_modules/async/lib/async.js:687:9)
    at DecompressZip.<anonymous> (/root/fabu.love-master/server/node_modules/ipa-metadata/index.js:38:11)
    at DecompressZip.emit (events.js:182:13)
    at DecompressZip.EventEmitter.emit (domain.js:442:20)
    at /root/fabu.love-master/server/node_modules/decompress-zip/lib/decompress-zip.js:125:14
    at _fulfilled (/root/fabu.love-master/server/node_modules/q/q.js:854:54)
    at /root/fabu.love-master/server/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/root/fabu.love-master/server/node_modules/q/q.js:816:13)
    at /root/fabu.love-master/server/node_modules/q/q.js:624:44
    at runSingle (/root/fabu.love-master/server/node_modules/q/q.js:137:13)

**Comment by 317482454** [comment]
我检查了代码，错误是由parseIpa导致的，但是我使用你们的测试网站能正常上传ipa，安卓无问题

进入了
 try {
                const environment = data.provisioning.Entitlements['aps-environment']
                const active = data.provisioning.Entitlements['beta-reports-active']

                if (environment == 'production') {
                    info.appLevel = active ? 'appstore' : 'enterprise'
                } else {
                    info.appLevel = 'develop'
                }
            } catch (err) {
                info.appLevel = 'develop'
                reject("应用未签名,暂不支持")
            }

这个该如何解决？

**Comment by zakiso** [comment]
你是什么系统的?

**Comment by 317482454** [comment]
本地是macOS 10.13.6

服务器是centos 7

**Comment by zakiso** [comment]
你本地的mac 和服务器的centos 都报错吗? 测试服务器正常?

**Comment by 317482454** [comment]
我本地跟服务器都无法解析ipa，但是fabu.love可以解析，是一个IPA文件

**Comment by 317482454** [comment]
ipa 解析出来的数据，错误提示是：Callback must be a function
{ metadata:
   { UIRequiresFullScreen: true,
     CFBundleInfoDictionaryVersion: '6.0',
     'UISupportedInterfaceOrientations~ipad':
      [ 'UIInterfaceOrientationPortrait',
        'UIInterfaceOrientationLandscapeLeft',
        'UIInterfaceOrientationPortraitUpsideDown',
        'UIInterfaceOrientationLandscapeRight' ],
     DTPlatformVersion: '11.4',
     CFBundleName: 'Nxt Wallet',
     DTSDKName: 'iphoneos11.4',
     CFBundleIcons: { CFBundlePrimaryIcon: [Object] },
     CFBundleDisplayName: 'Nxt Wallet',
     LSRequiresIPhoneOS: true,
     DTSDKBuild: '15F79',
     NSCameraUsageDescription: 'The camera is used to scan QR codes.',
     CFBundleShortVersionString: '1.0.6',
     CFBundleSupportedPlatforms: [ 'iPhoneOS' ],
     UISupportedInterfaceOrientations:
      [ 'UIInterfaceOrientationPortrait',
        'UIInterfaceOrientationLandscapeLeft',
        'UIInterfaceOrientationLandscapeRight' ],
     BuildMachineOSBuild: '17E199',
     DTPlatformBuild: '15F79',
     CFBundlePackageType: 'APPL',
     MinimumOSVersion: '9.0',
     CFBundleDevelopmentRegion: 'English',
     DTXcodeBuild: '9F2000',
     CFBundleVersion: '1.0.6',
     UILaunchImageFile: 'LaunchImage',
     UILaunchImages:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     UIDeviceFamily: [ 1, 2 ],
     CFBundleIdentifier: 'io.nxt.wallet',
     DTXcode: '0941',
     NSAppTransportSecurity: { NSAllowsArbitraryLoads: true },
     CFBundleExecutable: 'Nxt Wallet',
     'NSMainNibFile~ipad': '',
     'CFBundleIcons~ipad': { CFBundlePrimaryIcon: [Object] },
     CFBundleSignature: '????',
     DTPlatformName: 'iphoneos',
     DTCompiler: 'com.apple.compilers.llvm.clang.1_0'
  }
 }


我尝试在命令行进行也会产生一样的错误：
ipa 1535788502451-syt_Nxt\ WalletTarget_resigned_resigned.ipa 

错误：Callback must be a function

**Comment by zakiso** [comment]
不好意思 现在没时间看, 你先尝试用ubuntu试试, fabu.love用的ubuntu部署的, 稍后有时间的时候 我看看

**Comment by 317482454** [comment]
嗯，好的不急

**Comment by kengichan** [comment]
好像是 node 版本 问题，ipa-metadata 在 node 10上不行， 换 node 9/8  的运行环境试试吧

**Comment by 317482454** [comment]
成功了谢谢
