### ISSUE TITLE
上传ipa报错 Callback must be a function

### ISSUE THREAD

**Issue by leopardpan** [HeadingMobile/fabu.love#19]
您好，
我在本地测试环境上传iOS 安装包ipa时报错，请问下是什么问题？

本机操作流程

* mongoDB启动成功
* server启动成功
* client启动成功
* 在本机登录 `爱发布` 成功，上传`.ipa`时报错.
* .ipa 大小：9.8M
* 在[Demo fabu.love](https://fabu.love/apps)上提交是没问题的

本机环境:
```
macOS -v 10.13.4
db version v4.0.2
node -v v10.4.1
pm2 -v 3.1.2
```

报错信息：
```
Process API POST /api/apps/5b98d240574cf7230d86bc68/upload...
Process API error...
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:159:9)
    at Object.fs.exists (fs.js:237:3)
    at CertDownloader.pem (/Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_cert-downloader@0.1.0@cert-downloader/index.js:96:18)
    at CertDownloader.verify (/Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_cert-downloader@0.1.0@cert-downloader/index.js:131:11)
    at module.exports (/Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_provisioning@1.4.0@provisioning/index.js:7:10)
    at /Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_async@1.2.1@async/lib/async.js:731:23
    at /Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_async@1.2.1@async/lib/async.js:673:13
    at /Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_async@1.2.1@async/lib/async.js:230:13
    at _arrayEach (/Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_async@1.2.1@async/lib/async.js:81:9)
    at _each (/Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_async@1.2.1@async/lib/async.js:72:13)
    at async.forEachOf.async.eachOf (/Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_async@1.2.1@async/lib/async.js:229:9)
    at _parallel (/Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_async@1.2.1@async/lib/async.js:672:9)
    at Object.async.parallel (/Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_async@1.2.1@async/lib/async.js:687:9)
    at DecompressZip.<anonymous> (/Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_ipa-metadata@1.4.0@ipa-metadata/index.js:38:11)
    at DecompressZip.emit (events.js:182:13)
    at DecompressZip.EventEmitter.emit (domain.js:442:20)
    at /Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_decompress-zip@0.2.0@decompress-zip/lib/decompress-zip.js:125:14
    at _fulfilled (/Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_q@1.5.1@q/q.js:854:54)
    at /Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_q@1.5.1@q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_q@1.5.1@q/q.js:816:13)
    at /Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_q@1.5.1@q/q.js:624:44
    at runSingle (/Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_q@1.5.1@q/q.js:137:13)
    at flush (/Users/leopardpan/Desktop/Tool/LoveFabu/server/node_modules/_q@1.5.1@q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Process API GET /api/apps/5b98d240574cf7230d86bc68...
```

**Comment by zakiso** [comment]
node版本不对

**Comment by leopardpan** [comment]
好的，谢谢

**Comment by leopardpan** [comment]
node 版本切换到了v9.0.0了。
但是打开网页的时候报错 "请检查网络设置" .
如果我继续上传 `.ipa` 安装包时，页面卡在 `正在上传中 ...100% ` 就不动了。

**Comment by zakiso** [comment]
你用pm2启动的,还是直接在本地使用 npm start运行的Server端呢?

**Comment by leopardpan** [comment]
我是直接在server目录下使用的npm start运行。

我把node版本切换到了v8.9.3还是不行，刷新页面的时候还是报错 “请检查网络设置”。

我把本机node v10 删掉了，然后重新下了v8.9.3，请看下面的操作步骤.


### 启动 DB

$ ./mongo

```
MongoDB shell version: 3.2.4
connecting to: test
Server has startup warnings: 
2018-09-13T10:18:07.599+0800 I CONTROL  [initandlisten] 
2018-09-13T10:18:07.599+0800 I CONTROL  [initandlisten] ** WARNING: soft rlimits too low. Number of files is 256, should be at least 1000
```
### 启动 server

➜  $ server node -v
```
v8.9.3
```
➜  $ server cnpm install
```
⠸ [18/40] Installing verror@1.6.0
WARN node unsupported "node@v8.9.3" is incompatible with ipa-metadata@1.4.0 › entitlements@1.2.0 › simple-plist@0.0.4 › plist@1.1.0 › xmlbuilder@2.2.1, expected node@0.8.x || 0.10.x
⠧ [19/40] Installing repeat-element@^1.1.2[pm2@2.10.4 › gkt@https://tgz.pm2.io/gkt-1.0.0.tgz] install gkt from remote https://tgz.pm2.io/gkt-1.0.0.tgz, may be very slow, please keep patience
✔ Installed 40 packages
✔ Linked 563 latest versions
  ACTION binding_gyp_ndtp_target_build_ndtp .
  TOUCH Release/obj.target/ndtp.stamp
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.0/bcrypt_lib-v3.0.0-node-v57-darwin-x64-unknown.tar.gz
node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.0/bcrypt_lib-v3.0.0-node-v57-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.0/bcrypt_lib-v3.0.0-node-v57-darwin-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.0 and node@8.9.3 (node-v57 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.0/bcrypt_lib-v3.0.0-node-v57-darwin-x64-unknown.tar.gz 
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
  COPY /Users/leopardpan/Desktop/Tool/fabuLove/server/node_modules/_bcrypt@3.0.0@bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
[fsevents] Success: "/Users/leopardpan/Desktop/Tool/fabuLove/server/node_modules/_fsevents@1.2.4@fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
✔ Run 3 scripts
peerDependencies WARNING eslint-config-airbnb@^16.1.0 requires a peer of eslint-plugin-jsx-a11y@^6.0.2 but none was installed
peerDependencies WARNING eslint-config-airbnb@^16.1.0 requires a peer of eslint-plugin-react@^7.4.0 but none was installed
deprecate jsonwebtoken@7.4.3 › joi@6.10.1 › hoek@2.x.x The major version is no longer supported. Please update to 4.x or newer
deprecate ipa-metadata@1.4.0 › glob@5.0.10 › minimatch@^2.0.1 Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
deprecate ipa-metadata@1.4.0 › decompress-zip@0.2.0 › graceful-fs@^3.0.0 please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
deprecate ipa-metadata@1.4.0 › entitlements@1.2.0 › simple-plist@0.0.4 › plist@1.1.0 › xmlbuilder@2.2.1 › lodash-node@~2.4.1 This package is discontinued. Use lodash@^4.0.0.
Recently updated (since 2018-09-06): 15 packages (detail see file /Users/leopardpan/Desktop/Tool/fabuLove/server/node_modules/.recently_updates.txt)
  Today:
    → koa@2.5.3 › cookies@0.7.2 › keygrip@~1.0.2(1.0.3) (11:41:52)
    → lodash@^4.17.4(4.17.11) (02:32:16)
    → babel-preset-env@1.7.0 › browserslist@3.2.8 › electron-to-chromium@^1.3.47(1.3.67) (08:02:24)
✔ All packages installed (708 packages installed from npm registry, 1 packages installed from remote url, used 20s(network 8s), speed 814.37kB/s, json 602(6.71MB), tarball 0B)
```

➜  $ server npm start
```
> fabu@1.0.0 start /Users/leopardpan/Desktop/Tool/fabuLove/server
> babel-node index.js

process controller: app.js...
mongodb://localhost:27017/fabulove
{"updateMode":{"type":"string","require":true},"versionId":{"type":"string","description":"如果传入了versionId则表示设置某个版本的更新方式"}}
{"shortUrl":"string","installWithPwd":"boolean","installPwd":"string","autoPublish":"boolean"}
{"installUrl":"string","showOnDownloadPage":"boolean","changelog":"string","updateMode":{"type":"string"}}
{"updateMode":{"type":"string"},"ipType":{"type":"string"},"ipList":{"type":"string"},"downloadCountLimit":{"type":"number"}}
{"versionId":{"type":"string","require":true},"versionCode":{"type":"string","require":true},"release":{"type":"bool","require":true}}
{"strategy":{"type":"object","properties":{"updateMode":{"type":"string"},"ipType":{"type":"string"},"ipList":{"type":"string"},"downloadCountLimit":{"type":"number"}}},"version":{"type":"object","properties":{"versionId":{"type":"string","require":true},"versionCode":{"type":"string","require":true},"release":{"type":"bool","require":true}}}}
{"versionId":{"type":"string","require":true},"versionCode":{"type":"string","require":true},"release":{"type":"bool","require":true}}
[Function: AppRouter]
process controller: auth.js...
{"username":{"type":"string","required":true},"password":{"type":"string","required":true}}
{"username":{"type":"string","required":true},"password":{"type":"string","required":true},"email":{"type":"string","required":true}}
{"oldpwd":{"type":"string","require":true},"newpwd":{"type":"string","require":true}}
{"mobile":{"type":"string"},"qq":{"type":"string"},"company":{"type":"string"},"career":{"type":"string"}}
{"email":{"type":"string","required":true}}
[Function: AuthRouter]
process controller: message.js...
[Function: MessageRouter]
process controller: team.js...
{"name":{"type":"string","required":true},"icon":{"type":"string","required":false}}
{"memberId":{"type":"string","required":true},"role":{"type":"string","required":true,"description":"传入manager或者guest"}}
{"emailList":{"type":"array","items":{"type":"string"},"description":"邮箱列表","required":true},"role":{"type":"string","required":true,"description":"成员角色manager/guest"}}
{"name":{"type":"string","required":true}}
[Function: TeamRouter]
process controller: upload.js...
[Function: UploadRouter]
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md index.js:44:5
App is listening on 9898.
数据库连接成功
```

### 启动client


➜ $ client source ~/.bash_profile

➜  $ client node -v     
```
v8.9.3
```

➜ $ client cnpm install          
```
✔ Installed 57 packages
✔ Linked 845 latest versions
[fsevents] Success: "/Users/leopardpan/Desktop/Tool/fabuLove/client/node_modules/_fsevents@1.2.4@fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
Cached binary found at /Users/leopardpan/.npminstall_tarball/node-sass/4.9.3/darwin-x64-57_binding.node
Binary found at /Users/leopardpan/Desktop/Tool/fabuLove/client/node_modules/_node-sass@4.9.3@node-sass/vendor/darwin-x64-57/binding.node
Testing binary
Binary is fine
✔ Run 3 scripts
peerDependencies link ajv@5.5.2 in /Users/leopardpan/Desktop/Tool/fabuLove/client/node_modules/_ajv-keywords@2.1.1@ajv-keywords unmet with /Users/leopardpan/Desktop/Tool/fabuLove/client/node_modules/ajv(6.5.3)
peerDependencies WARNING less-loader@^4.1.0 requires a peer of less@^2.3.1 || ^3.0.0 but none was installed
deprecate autoprefixer@7.2.6 › browserslist@^2.11.3 Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
deprecate css-loader@0.28.11 › cssnano@3.10.0 › autoprefixer@6.7.7 › browserslist@^1.7.6 Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
deprecate webpack-bundle-analyzer@2.13.1 › bfj-node4@^5.2.0 Switch to the `bfj` package for fixes and new features!
Recently updated (since 2018-09-06): 9 packages (detail see file /Users/leopardpan/Desktop/Tool/fabuLove/client/node_modules/.recently_updates.txt)
  Today:
    → autoprefixer@7.2.6 › browserslist@2.11.3 › electron-to-chromium@^1.3.30(1.3.67) (08:02:24)
    → babel-eslint@8.2.6 › @babel/traverse@7.0.0-beta.44 › lodash@^4.2.0(4.17.11) (02:32:16)
✔ All packages installed (1039 packages installed from npm registry, used 11s(network 9s), speed 838.7kB/s, json 902(7.72MB), tarball 0B)
```

➜ $ client npm run build
```
> app-publisher@1.0.0 build /Users/leopardpan/Desktop/Tool/fabuLove/client
> node build/build.js

Hash: b3b11b8b7b652b4abf77
Version: webpack 3.12.0
Time: 29445ms
                                              Asset       Size  Chunks                    Chunk Names
                static/js/2.d57c4f7371665ee42c09.js    39.3 kB       2  [emitted]         
                  static/img/bg_picture.07f3585.png     279 kB          [emitted]  [big]  
                  static/fonts/icomoon.d37bb3e.woff    12.9 kB          [emitted]         
                   static/fonts/icomoon.f0ddd02.eot      13 kB          [emitted]         
                   static/fonts/icomoon.aa27446.ttf    12.9 kB          [emitted]         
                     static/img/icomoon.754976f.svg    43.5 kB          [emitted]         
                   static/img/empty_app.576448a.png    15.6 kB          [emitted]         
               static/img/ic_mobilphone.0bb8e79.png     127 kB          [emitted]         
                         static/img/box.43c604b.png    19.9 kB          [emitted]         
                static/js/0.ad268373d031595924e1.js     1.9 kB       0  [emitted]         vendor-async
                static/js/1.0f7ec81ab4f1580d5e6b.js      42 kB    1, 6  [emitted]         
             static/fonts/element-icons.6f0a763.ttf      11 kB          [emitted]         
                static/js/3.2b47d21e19c9f81daeec.js    35.7 kB       3  [emitted]         
                static/js/4.af68def0b6735a9d90f8.js    26.8 kB       4  [emitted]         
                static/js/5.4b312d5b85d29b1fe971.js    25.7 kB       5  [emitted]         
                static/js/6.8141da55dfb5da377688.js    18.4 kB       6  [emitted]         
                static/js/7.c6e38613cf535493a111.js    6.06 kB       7  [emitted]         
           static/js/vendor.700b10424c186b1e1543.js     773 kB       8  [emitted]  [big]  vendor
              static/js/app.c36e4ac73526e0e4fbfe.js    11.5 kB       9  [emitted]         app
         static/js/manifest.d9155e1809627be6e2ac.js    1.58 kB      10  [emitted]         manifest
static/css/app.f00c4959dadd242201fb2b6db420f2f3.css     247 kB       9  [emitted]         app
                                         index.html  765 bytes          [emitted]         

  Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.
```

➜ $ client npm run dev
```
> app-publisher@1.0.0 dev /Users/leopardpan/Desktop/Tool/fabuLove/client
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 95% emitting                                                                           

 DONE  Compiled successfully in 18230ms                                                                               14:50:14

 I  Your application is running here: http://0.0.0.0:3009
```

### 打开浏览器输入  http://0.0.0.0:3009

报错 "请检查网络设置" .
继续上传 .ipa 安装包，页面卡在 正在上传中 ...100% 就不动了。

**Comment by Darren-chenchen** [comment]
你的意思是不是报错的情况下，界面一直展示 “正在上传中”，如果是这样，可能是报错的情况下我没有及时移除这个页面，我检查下。

**Comment by zakiso** [comment]
你可以贴一下你 server里面的config.js文件的内容吗?

**Comment by leopardpan** [comment]
@Darren-chenchen  打开页面报错"请检查网络设置"  , 然后我继续上传， 页面卡在 正在上传中 ...100% 就不动了。

**Comment by leopardpan** [comment]
@zakiso server里面config.js的内容

```
var fs = require("fs")
var path = require("path")


const common = {
    baseUrl: process.env.FABU_BASE_URL || "https://127.0.0.1:9898", //baseUrl应用请求的url地址,比如https://fabu.love
    port: process.env.FABU_PORT || "9898", //server运行的端口
    apiPrefix: 'api',
    fileDir: process.env.FABU_UPLOAD_DIR || path.join(__dirname, ".."), //上传文件的存放目录
    secret: process.env.FABU_SECRET || "secretsecret", //secret
    dbUser: process.env.FABU_DBUSER || undefined, //数据库用户 (没有开启mongodb用户认证的可以不填写)
    dbPass: process.env.FABU_DBPWD || undefined, //数据库密码 (没有开启mongodb用户认证的可以不填写)
    dbName: process.env.FABU_DB_NAME || "fabulove", //数据库名称
    dbHost: process.env.FABU_DB_HOST || "localhost", //数据库地址
    dbPort: process.env.FABU_DB_PORT || "27017", //数据库端口

    emailService: process.env.FABU_EMAIL_SERVICE || "qq", //邮件相关配置 用于找回密码和邀请团队成员发送邮件
    emailUser: process.env.FABU_EMAIL_USER || "",
    emailPass: process.env.FABU_EMAIL_PASS || "",
    emailPort: process.env.FABU_EMAIL_PORT || "587",

    allowRegister: boolConfig(process.env.FABU_ALLOW_REGISTER || "true"), //是否允许用户注册,为否则后端注册接口不可用

    openLdap: boolConfig(process.env.FABU_ALLOW_LDAP || "false"), //是否开启ldap 默认是false 如果公司没有ldap服务可以不用理会
    ldapServer: process.env.FABU_LDAP_URL || "", //ldap server url
    ldapUserDn: process.env.FABU_LDAP_USERDN || "", //ldap管理员dn 也就是管理员用户名
    ldapBindCredentials: process.env.FABU_LDAP_CREDENTIALS || "", //ldap管理员密码
    ldapBase: process.env.FABU_LDAP_BASE || "", //ldap base


};

function boolConfig(str) {
    if (str == 'true') {
        return true
    } else {
        return false
    }
}


export default common;
```

[https://github.com/HeadingMobile/fabu.love](https://github.com/HeadingMobile/fabu.love) 项目是下载下来的不是clone的，然后直接运行没做其他处理。

**Comment by zakiso** [comment]
那个请检查网络连接,应该是跨域的问题, 你浏览器访问的是http://0.0.0.0:3009, 但是前端js请求的是https://127.0.0.1:9898, 这个地址 你可以把浏览器的跨域限制先关掉一下. 顺便把server config的baseUrl的https改成http 试试

**Comment by leopardpan** [comment]
关掉跨域限制、server config的baseUrl的https改成http  后还是不行，跟之前的一样。 根目录下的 fabu_nginx.conf 文件是否要修改？


根据这个[教程](http://blog.mingsixue.com/debug/Chrome-cross-domain-set.html)把跨域设置关了，但是我也没确定是否一定关闭成功，重启电脑后输入命令弹出一个界面感觉应该是跨域了。

```
MAC 上Chrome跨域设置
1、新建一个目录，用于存放保存关闭安全策略后的用户信息的，名称和位置随意。

2、在终端中输入：open -n /Applications/Google\ Chrome.app/ --args --disable-web-security --user-data-dir=/Users/Vic/Documents/MyChromeDevUserData

3、将第2步的 /Users/Vic/Documents/MyChromeDevUserData 替换为第1步的目录。

MAC重启后需要重新按上面第2步设置跨域。

```

**Comment by zakiso** [comment]
你在本地运行的话 没用上那个 fabu_nginx.conf的

**Comment by leopardpan** [comment]
我使用Chrome还是不行，但是使用safari可以打开，可以上传ipa安装包，也可以生产下载页面。但是使用手机下载的时候还是不行。进入下载页面后是这样的，没有下载按钮，不清楚是我的配置问题还是什么。

BASE_URL http 和https都试过

![6491536836999_ pic](https://user-images.githubusercontent.com/11239874/45485029-b7176880-b788-11e8-9261-218bd2ac88a1.jpg)

**Comment by zakiso** [comment]
应该就是跨域问题, 你可以试试部署到 同一个域下测试一下. 也可以在首页左下角点Api文档进入swagger,测试一下后端的接口是否有问题, 在swagger中 调用登录接口成功之后,在顶部的authorize里面输入 Bearer xxxxx, xxx填你的token ,就可以使用swagger测试了.

**Comment by Darren-chenchen** [comment]
@leopardpan 关于上传至100%不动的情况，1.确定服务器已经开启  2.请你打开调试器，把响应的信息传递给我们，目前不好重现问题。

**Comment by leopardpan** [comment]
昨天是用safari打开后，上传ipa成功。今天重启
