### ISSUE TITLE
Unhandled rejection Error: invalid signature: 0xff8

### ISSUE THREAD

**Issue by lzw122333** [HeadingMobile/fabu.love#55]
上传包100%之后，报了如下错误：
`Unhandled rejection Error: invalid signature: 0xff8
    at /opt/server/node_modules/unzipper/lib/parse.js:62:26
    at tryCatcher (/opt/server/node_modules/unzipper/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/server/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/opt/server/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/opt/server/node_modules/unzipper/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/opt/server/node_modules/unzipper/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/opt/server/node_modules/unzipper/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/server/node_modules/unzipper/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)`

**Comment by caibudaola** [comment]
报错之后应用列表icon丢失，下载应用显示404

**Comment by caibudaola** [comment]
node版本尝试了：8.14.0，9.0.0，9.9.0，11.10.1

**Comment by zakiso** [comment]
您是用的什么操作系统？

**Comment by caibudaola** [comment]
我们用的是 Centos7，用 docker 镜像，也是这个报错

**Comment by caibudaola** [comment]
还有，现在您发布的demo站上传包非常满，失败率很高

**Comment by zakiso** [comment]
麻烦提供一下app包 方便吗？

**Comment by zakiso** [comment]
测试网站只有1M带宽 是比较慢 而且还跑了好几个应用

**Comment by caibudaola** [comment]
发您邮箱了

**Comment by 751811032** [comment]
您好，请问该问题有解决吗。应该不是包的问题，我试了很多个包都这样
在zip.parse那里报错

**Comment by lzw122333** [comment]
没有解决， 作者没有回复我了。

**Comment by zakiso** [comment]
已经更新了程序， 在现在的测试网站里 还存在这个问题？

**Comment by 751811032** [comment]
看到了，已经下载最新的试了，但是客户端 npm install一直过不去。windows和mac都过不去。到一半就安装不动了

**Comment by zakiso** [comment]
安装cnpm 用cnpm install 替代 ，一般是网络问题

**Comment by 751811032** [comment]
可以了，现在没问题了

**Comment by 751811032** [comment]
感谢感谢

**Comment by zakiso** [comment]
fixed
