### ISSUE TITLE
本地MAC环境以及云上CENTOS均上传报错，错误码:EACCES

### ISSUE THREAD

**Issue by ztan9766** [HeadingMobile/fabu.love#59]
console 错误信息如下，是有什么权限配置问题码？

{ Error: spawn EACCES
    at ChildProcess.spawn (internal/child_process.js:330:11)
    at exports.spawn (child_process.js:500:9)
    at exports.execFile (child_process.js:210:15)
    at parseApk (/Users/tan/Projects/fabu/server/library/apkparser/apkparser.js:19:10)
    at Promise (/Users/tan/Projects/fabu/server/controllers/upload.js:277:9)
    at new Promise (<anonymous>)
    at parseApk (/Users/tan/Projects/fabu/server/controllers/upload.js:276:12)
    at parseAppAndInsertToDB (/Users/tan/Projects/fabu/server/controllers/upload.js:116:22)
    at upload (/Users/tan/Projects/fabu/server/controllers/upload.js:75:28)
    at <anonymous> errno: 'EACCES', code: 'EACCES', syscall: 'spawn' }

**Comment by ztan9766** [comment]
解决了将项目文件夹权限修改为 chmod -R a+rwx /path_to_project/project_name
