### ISSUE TITLE
server npm install bcrypt failed

### ISSUE THREAD

**Issue by solrex** [HeadingMobile/fabu.love#6]
```
3671 verbose stack Error: bcrypt@3.0.0 install: `node-pre-gyp install --fallback-to-build`
3671 verbose stack spawn ENOENT
3671 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
3671 verbose stack     at emitTwo (events.js:87:13)
3671 verbose stack     at ChildProcess.emit (events.js:172:7)
3671 verbose stack     at maybeClose (internal/child_process.js:821:16)
3671 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
3672 verbose pkgid bcrypt@3.0.0
3673 verbose cwd /opt/fabu.love/server
3674 error Linux 4.4.0-127-generic
3675 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
3676 error node v4.2.6
3677 error npm  v3.5.2
3678 error file sh
3679 error code ELIFECYCLE
3680 error errno ENOENT
3681 error syscall spawn
3682 error bcrypt@3.0.0 install: `node-pre-gyp install --fallback-to-build`
3682 error spawn ENOENT
3683 error Failed at the bcrypt@3.0.0 install script 'node-pre-gyp install --fallback-to-build'.
3683 error Make sure you have the latest version of node.js and npm installed.
3683 error If you do, this is most likely a problem with the bcrypt package,
3683 error not with npm itself.
3683 error Tell the author that this fails on your system:
3683 error     node-pre-gyp install --fallback-to-build
3683 error You can get information on how to open an issue for this project with:
3683 error     npm bugs bcrypt
3683 error Or if that isn't available, you can get their info via:
3683 error     npm owner ls bcrypt
3683 error There is likely additional logging output above.
3684 verbose exit [ 1, true ]
```

**Comment by solrex** [comment]
原来是我的 npm 版本太老了。
