### ISSUE TITLE
docker安装时的错误

### ISSUE THREAD

**Issue by ytzk507** [HeadingMobile/fabu.love#61]
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::9898
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Application.listen (/opt/server/node_modules/_koa@2.7.0@koa/lib/application.js:65:19)
    at Object.<anonymous> (/opt/server/index.js:73:20)
    at Module._compile (module.js:643:30)
    at loader (/opt/server/node_modules/_babel-register@6.26.0@babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/opt/server/node_modules/_babel-register@6.26.0@babel-register/lib/node.js:154:7)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at Object.<anonymous> (/opt/server/node_modules/_babel-cli@6.26.0@babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fabu@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fabu@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-18T05_53_30_828Z-debug.log

实在搞不明白是什么原因了。有人知道吗？

**Comment by ytzk507** [comment]
MAC

**Comment by zakiso** [comment]
已解决，请使用最新版本
