### ISSUE TITLE
Docker部署后，访问不到502

### ISSUE THREAD

**Issue by lhalcyon** [headingmobile/fabu.love#85]

**Comment by lhalcyon** [comment]
拉倒本地运行后报错  
![image](https://user-images.githubusercontent.com/21357951/61195344-fe002280-a6f9-11e9-82b5-23dc8d6dd759.png)

**Comment by zakiso** [comment]
应该是你的docker有问题，你试试用你的docker运行其他项目能行不。

**Comment by lhalcyon** [comment]
@zakiso  我在服务器上后 是502 , 在本地是如上截图的错误.

**Comment by zakiso** [comment]
你可以提供一下服务器上的 docker日志

**Comment by lhalcyon** [comment]
Traceback (most recent call last):
  File "site-packages/dockerpycreds/store.py", line 74, in _execute
  File "subprocess.py", line 336, in check_output
  File "subprocess.py", line 418, in run
subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-osxkeychain', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/docker/auth.py", line 129, in _resolve_authconfig_credstore
  File "site-packages/dockerpycreds/store.py", line 35, in get
  File "site-packages/dockerpycreds/store.py", line 87, in _execute
dockerpycreds.errors.StoreError: Credentials store docker-credential-osxkeychain exited with "The user name or passphrase you entered is not correct.".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 127, in perform_command
  File "compose/cli/main.py", line 1080, in up
  File "compose/cli/main.py", line 1076, in up
  File "compose/project.py", line 475, in up
  File "compose/service.py", line 342, in ensure_image_exists
  File "compose/service.py", line 1082, in build
  File "site-packages/docker/api/build.py", line 251, in build
  File "site-packages/docker/api/build.py", line 307, in _set_auth_headers
  File "site-packages/docker/auth.py", line 96, in resolve_authconfig
  File "site-packages/docker/auth.py", line 146, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-osxkeychain exited with "The user name or passphrase you entered is not correct.".',)


这个是我本地的错误, 貌似是数据库auth出错

**Comment by lhalcyon** [comment]
@zakiso  本地报错解决了. 部署已经成功,但是注册和登录请求一直loading

**Comment by lhalcyon** [comment]
而且官网主页提供的demo也是无法注册和登录呢.

**Comment by lihp2014** [comment]
想问下是怎么解决无法注册和登录问题的？@lhalcyon
