### ISSUE TITLE
上传后服务报错且提示未检测到版本信息，

### ISSUE THREAD

**Issue by itstudying** [headingmobile/fabu.love#95]
上传apk后服务报如下错误，打开下载地址提示未检测到版本信息

Process API GET /api/apps/5dce184a4fc8cb6e3137e970...
res/mipmap-xxhdpi-v4/icon_hk.jpg
Unhandled rejection Error: invalid signature: 0xff8
    at /data/fabu.love/server/node_modules/_unzipper@0.9.15@unzipper/lib/parse.js:62:26
    at tryCatcher (/data/fabu.love/server/node_modules/_bluebird@3.4.7@bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/data/fabu.love/server/node_modules/_bluebird@3.4.7@bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/data/fabu.love/server/node_modules/_bluebird@3.4.7@bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/data/fabu.love/server/node_modules/_bluebird@3.4.7@bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/data/fabu.love/server/node_modules/_bluebird@3.4.7@bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/data/fabu.love/server/node_modules/_bluebird@3.4.7@bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/data/fabu.love/server/node_modules/_bluebird@3.4.7@bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)

**Comment by li-keli** [comment]
我也是未检测到版本信息，你那边是怎么解决的？
